package com.zxdz.car.base.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zxdz.car.main.model.domain.CardInfo;
import com.zxdz.car.main.model.domain.CarTravelRecord;
import com.zxdz.car.main.model.domain.AreaInfo;

import com.zxdz.car.base.dao.CardInfoDao;
import com.zxdz.car.base.dao.CarTravelRecordDao;
import com.zxdz.car.base.dao.AreaInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardInfoDaoConfig;
    private final DaoConfig carTravelRecordDaoConfig;
    private final DaoConfig areaInfoDaoConfig;

    private final CardInfoDao cardInfoDao;
    private final CarTravelRecordDao carTravelRecordDao;
    private final AreaInfoDao areaInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardInfoDaoConfig = daoConfigMap.get(CardInfoDao.class).clone();
        cardInfoDaoConfig.initIdentityScope(type);

        carTravelRecordDaoConfig = daoConfigMap.get(CarTravelRecordDao.class).clone();
        carTravelRecordDaoConfig.initIdentityScope(type);

        areaInfoDaoConfig = daoConfigMap.get(AreaInfoDao.class).clone();
        areaInfoDaoConfig.initIdentityScope(type);

        cardInfoDao = new CardInfoDao(cardInfoDaoConfig, this);
        carTravelRecordDao = new CarTravelRecordDao(carTravelRecordDaoConfig, this);
        areaInfoDao = new AreaInfoDao(areaInfoDaoConfig, this);

        registerDao(CardInfo.class, cardInfoDao);
        registerDao(CarTravelRecord.class, carTravelRecordDao);
        registerDao(AreaInfo.class, areaInfoDao);
    }
    
    public void clear() {
        cardInfoDaoConfig.clearIdentityScope();
        carTravelRecordDaoConfig.clearIdentityScope();
        areaInfoDaoConfig.clearIdentityScope();
    }

    public CardInfoDao getCardInfoDao() {
        return cardInfoDao;
    }

    public CarTravelRecordDao getCarTravelRecordDao() {
        return carTravelRecordDao;
    }

    public AreaInfoDao getAreaInfoDao() {
        return areaInfoDao;
    }

}
